### ISSUE TITLE
Level 2 - Module 8，error：Sorry, this action is not available for your app.

### ISSUE THREAD

**Issue by joy12202018** [actions-on-google/codelabs-nodejs#18]
According to the tutorial (https://codelabs.developers.google.com/codelabs/actions-2/index.html#7), after completing step 8, test on the simulator, when it comes to reply "Would you like to hear some Fake colors?" When I type yes, I get the following error:
Sorry, this action is not available for your app.
In the simulator, you are only able to invoke actions that you have added to your app. For more information on how to invoke your app, click here https://developers.google.com/actions/discovery/explicit

How can I solve it?

**Comment by taycaldwell** [comment]
See the answer [here](https://github.com/actions-on-google/codelabs-nodejs/issues/8#issuecomment-407867041), and let me know if that fixes your issue.

**Comment by smishra2** [comment]
@joy12202018 As mentioned in the other issue, this is because your Action is ending the dialog right before you say "yes". The dialog will end for 1 of 2 reasons.

1) You checked the box that says "Set this intent as end of conversation" at the bottom of the Dialogflow intent UI for the intent which was triggered right before you said "yes". 

2) In the intent handler for `favorite color`, you are using `conv.close` instead of `conv.ask`.

Let me know if that works and reopen the comment if you're still having issues.
