### ISSUE TITLE
Simulator message is different

### ISSUE THREAD

**Issue by surbheesehgal** [actions-on-google/codelabs-nodejs#21]
Screenshot of simulator in the codelab documentation :
![screen shot 2018-09-14 at 11 23 13 am](https://user-images.githubusercontent.com/27842227/45568117-9b57a500-b810-11e8-8afa-d838bac4d432.png)

The message that shows up during testing is pasted below because the app has not been published yet. 
<img width="1358" alt="screen shot 2018-09-14 at 11 21 18 am" src="https://user-images.githubusercontent.com/27842227/45568050-592e6380-b810-11e8-9813-ccbb7ea2ee07.png">

**Comment by lucaswadedavis** [comment]
Thanks for the notification surbheesehgal.

This is a minor cosmetic difference that has happened in the product since that screenshot was taken. If it were a bigger change or confusing, I'd take the time to update the screenshot, but it's just small enough that I'm going to call it basically okay, and close the issue.
