### ISSUE TITLE
Copy change (Firebase version)

### ISSUE THREAD

**Issue by shaunith** [actions-on-google/codelabs-nodejs#3]
Not sure if I overlooked something on this page: https://codelabs.developers.google.com/codelabs/actions-2/index.html#1. 

After installing firebase and running `firebase --version` I am on version `3.18.5`.  Which appears to be the correct version (as per the npm badge on https://github.com/firebase/firebase-tools) despite the copy reading 

> Make sure the version of the Firebase CLI is above 3.5.0 so that it has all the latest features required for Cloud Functions.

Have I misread or is this an error in the version number?

**Comment by Fleker** [comment]
Your version of Firebase tools is above the minimum required version, so you're fine.

**Comment by TrackMy** [comment]
Not sure why this was closed, it was never properly addressed. According to the page, the recommended minimum version is 3.5.0 but as of today, the latest version is 3.18.6. The page needs to be corrected so readers aren't chasing their tale trying to update firebase to a version that doesn't exist. Perhaps the author meant 3.18.5?

**Comment by Fleker** [comment]
3.18.6 is the latest version, and if you have that you're good. 3.5.0 is the minimum version to run the codelab. [Version 3.5.0](https://github.com/firebase/firebase-tools/releases?after=v3.6.0) was released last March and adds support for cloud functions, which is a key part of the codelab.

**Comment by mscheel** [comment]
This confused me too.  I read 3.5 as 3.50 in the context of 3.18 (now 19), in many domains 3.5 > 3.19.  

Perhaps this simple text change would ease confusion and be easier than changing your versioning semantics?

Change:

Make sure the version of the Firebase CLI is above 3.5.0 so that it has all the latest features required for Cloud Functions.

to:

Make sure the version of the Firebase CLI is above 3.5.0 ([March 2018](https://www.npmjs.com/package/firebase-tools)) so that it has all the latest features required for Cloud Functions.

**Comment by lucaswadedavis** [comment]
3.18.5 is above 3.5.0 following [semantic versioning norms](https://semver.org/). The documentation in the codelab is not incorrect.
