### ISSUE TITLE
Codelab does not work Level 1 part 6

### ISSUE THREAD

**Issue by rs146** [actions-on-google/codelabs-nodejs#8]
The simulator does not respond to a favourite colour. In fact, it doesn't seem that it works at all apart from the default welcome intent.

I get the error: 

`Sorry, this action is not available for your app.
In the simulator, you are only able to invoke actions that you have added to your app. For more information on how to invoke your app, click here https://developers.google.com/actions/discovery/explicit`

I have trained the favorite color intent and added the webhook as outlined but I still get the same response when I input a colour.

**Comment by mscheel** [comment]
If you are able to provide some screenshots of your interaction with the simulator and the Dialogflow console I can probably help you resolve this.  It might be best to post on [Stack Overflow](https://stackoverflow.com/questions/tagged/actions-on-google) as this is likely not an error in the codelab.  It could be, but I can tell you that I have followed the codelab instructions and not had the same error you list.  Let's figure it out!

**Comment by timetraveller05** [comment]
![screenshot from 2018-07-04 10-49-38](https://user-images.githubusercontent.com/29993120/42258182-114276f4-7f78-11e8-9e5f-7613d0461943.png)
This is the screenshot of the conversation with my google assistant with the same issue. Please help me out.

**Comment by mscheel** [comment]
Please share a screenshot of your intent in Dialogflow, both default welcome intent and favorite color.  Wild guess: is the "Set this intent as the end of the conversation" slider on, in the default welcome intent?  It would also help if you switched to the speaker surface, given the current simulator bug that does not speak the first TTS in the simulator as you are using it.  I would like to encourage you again to use Stack Overflow, I will be just as responsive there.

**Comment by smishra2** [comment]
Looking at this again, I think @mscheel is correct. It looks like the conversation is ending after the first turn of dialog (which means saying "Pink" won't work, as you're no longer in conversation). This may be because in your Default Welcome Intent you have checked a box at the bottom of the Dialogflow UI which ends the conversation when that intent is triggered (i.e. `Set this intent as end of conversation`). In this case, simply uncheck the box.

Please reopen this issue if you continue getting this error.
